const locations = [
  // Light World - Death Mountain - East
  {
    id: 'spiralCave',
    name: `Spiral Cave`,
    offset: 0x1fc,
    mask: 0x10,
  },
  {
    id: 'mimicCave',
    name: `Mimic Cave`,
    offset: 0x218,
    mask: 0x10,
  },
  {
    id: 'paradoxCaveLowerFarLeft',
    name: `Paradox Cave Lower - Far Left`,
    offset: 0x1de,
    mask: 0x10,
  },
  {
    id: 'paradoxCaveLowerLeft',
    name: `Paradox Cave Lower - Left`,
    offset: 0x1de,
    mask: 0x20,
  },
  {
    id: 'paradoxCaveLowerRight',
    name: `Paradox Cave Lower - Right`,
    offset: 0x1de,
    mask: 0x40,
  },
  {
    id: 'paradoxCaveLowerFarRight',
    name: `Paradox Cave Lower - Far Right`,
    offset: 0x1de,
    mask: 0x80,
  },
  {
    id: 'paradoxCaveLowerMiddle',
    name: `Paradox Cave Lower - Middle`,
    offset: 0x1df,
    mask: 0x01,
  },
  {
    id: 'paradoxCaveUpperLeft',
    name: `Paradox Cave Upper - Left`,
    offset: 0x1fe,
    mask: 0x10,
  },
  {
    id: 'paradoxCaveUpperRight',
    name: `Paradox Cave Upper - Right`,
    offset: 0x1fe,
    mask: 0x20,
  },
  {
    id: 'floatingIsland',
    name: `Floating Island`,
    offset: 0x285,
    mask: 0x40,
  },
  // Light World - Death Mountain - West
  {
    id: 'oldMan',
    name: `Old Man`,
    offset: 0x410,
    mask: 0x01,
  },
  {
    id: 'spectacleRockCave',
    name: `Spectacle Rock Cave`,
    offset: 0x1d5,
    mask: 0x04,
  },
  {
    id: 'etherTablet',
    name: `Ether Tablet`,
    offset: 0x411,
    mask: 0x01,
  },
  {
    id: 'spectacleRock',
    name: `Spectacle Rock`,
    offset: 0x283,
    mask: 0x40,
  },
  // Light World - North East
  {
    id: 'sahasrahlasHutLeft',
    name: `Sahasrahla's Hut - Left`,
    offset: 0x20a,
    mask: 0x10,
  },
  {
    id: 'sahasrahlasHutMiddle',
    name: `Sahasrahla's Hut - Middle`,
    offset: 0x20a,
    mask: 0x20,
  },
  {
    id: 'sahasrahlasHutRight',
    name: `Sahasrahla's Hut - Right`,
    offset: 0x20a,
    mask: 0x40,
  },
  {
    id: 'sahasrahla',
    name: `Sahasrahla`,
    offset: 0x410,
    mask: 0x10,
  },
  {
    id: 'kingZora',
    name: `King Zora`,
    offset: 0x410,
    mask: 0x02,
  },
  {
    id: 'potionShop',
    name: `Potion Shop`,
    offset: 0x411,
    mask: 0x20,
  },
  {
    id: 'zorasLedge',
    name: `Zora's Ledge`,
    offset: 0x301,
    mask: 0x40,
  },
  {
    id: 'waterfallFairyLeft',
    name: `Waterfall Fairy - Left`,
    offset: 0x228,
    mask: 0x10,
  },
  {
    id: 'waterfallFairyRight',
    name: `Waterfall Fairy - Right`,
    offset: 0x228,
    mask: 0x20,
  },
  // Light World - North West
  {
    id: 'masterSwordPedestal',
    name: `Master Sword Pedestal`,
    offset: 0x300,
    mask: 0x40,
  },
  {
    id: 'kingsTomb',
    name: `King's Tomb`,
    offset: 0x226,
    mask: 0x10,
  },
  {
    id: 'kakarikoTavern',
    name: `Kakariko Tavern`,
    offset: 0x206,
    mask: 0x10,
  },
  {
    id: 'chickenHouse',
    name: `Chicken House`,
    offset: 0x210,
    mask: 0x10,
  },
  {
    id: 'kakarikoWellTop',
    name: `Kakariko Well - Top`,
    offset: 0x05e,
    mask: 0x10,
  },
  {
    id: 'kakarikoWellLeft',
    name: `Kakariko Well - Left`,
    offset: 0x05e,
    mask: 0x20,
  },
  {
    id: 'kakarikoWellMiddle',
    name: `Kakariko Well - Middle`,
    offset: 0x05e,
    mask: 0x40,
  },
  {
    id: 'kakarikoWellRight',
    name: `Kakariko Well - Right`,
    offset: 0x05e,
    mask: 0x80,
  },
  {
    id: 'kakarikoWellBottom',
    name: `Kakariko Well - Bottom`,
    offset: 0x05e,
    mask: 0x01,
  },
  {
    id: 'blindsHideoutTop',
    name: `Blind's Hideout - Top`,
    offset: 0x23a,
    mask: 0x10,
  },
  {
    id: 'blindsHideoutLeft',
    name: `Blind's Hideout - Left`,
    offset: 0x23a,
    mask: 0x20,
  },
  {
    id: 'blindsHideoutRight',
    name: `Blind's Hideout - Right`,
    offset: 0x23a,
    mask: 0x40,
  },
  {
    id: 'blindsHideoutFarLeft',
    name: `Blind's Hideout - Far Left`,
    offset: 0x23a,
    mask: 0x80,
  },
  {
    id: 'blindsHideoutFarRight',
    name: `Blind's Hideout - Far Right`,
    offset: 0x23a,
    mask: 0x01,
  },
  {
    id: 'pegasusRocks',
    name: `Pegasus Rocks`,
    offset: 0x248,
    mask: 0x10,
  },
  {
    id: 'bottleMerchant',
    name: `Bottle Merchant`,
    offset: 0x3c9,
    mask: 0x02,
  },
  {
    id: 'magicBat',
    name: `Magic Bat`,
    offset: 0x411,
    mask: 0x80,
  },
  {
    id: 'sickKid',
    name: `Sick Kid`,
    offset: 0x410,
    mask: 0x04,
  },
  {
    id: 'lostWoodsHideout',
    name: `Lost Woods Hideout`,
    offset: 0x1c3,
    mask: 0x02,
  },
  {
    id: 'lumberjackTree',
    name: `Lumberjack Tree`,
    offset: 0x1c5,
    mask: 0x02,
  },
  {
    id: 'graveyardLedge',
    name: `Graveyard Ledge`,
    offset: 0x237,
    mask: 0x02,
  },
  {
    id: 'mushroom',
    name: `Mushroom`,
    offset: 0x411,
    mask: 0x10,
  },
  // Light World - South
  {
    id: 'floodgateChest',
    name: `Floodgate Chest`,
    offset: 0x216,
    mask: 0x10,
  },
  {
    id: 'linksHouse',
    name: `Link's House`,
    offset: 0x208,
    mask: 0x10,
  },
  {
    id: 'aginahsCave',
    name: `Aginah's Cave`,
    offset: 0x214,
    mask: 0x10,
  },
  {
    id: 'miniMoldormCaveFarLeft',
    name: `Mini Moldorm Cave - Far Left`,
    offset: 0x246,
    mask: 0x10,
  },
  {
    id: 'miniMoldormCaveLeft',
    name: `Mini Moldorm Cave - Left`,
    offset: 0x246,
    mask: 0x20,
  },
  {
    id: 'miniMoldormCaveRight',
    name: `Mini Moldorm Cave - Right`,
    offset: 0x246,
    mask: 0x40,
  },
  {
    id: 'miniMoldormCaveFarRight',
    name: `Mini Moldorm Cave - Far Right`,
    offset: 0x246,
    mask: 0x80,
  },
  {
    id: 'iceRodCave',
    name: `Ice Rod Cave`,
    offset: 0x240,
    mask: 0x10,
  },
  {
    id: 'hobo',
    name: `Hobo`,
    offset: 0x3c9,
    mask: 0x01,
  },
  {
    id: 'bombosTablet',
    name: `Bombos Tablet`,
    offset: 0x411,
    mask: 0x02,
  },
  {
    id: 'cave45',
    name: `Cave 45`,
    offset: 0x237,
    mask: 0x04,
  },
  {
    id: 'checkerboardCave',
    name: `Checkerboard Cave`,
    offset: 0x24d,
    mask: 0x02,
  },
  {
    id: 'miniMoldormCaveNPC',
    name: `Mini Moldorm Cave - NPC`,
    offset: 0x247,
    mask: 0x04,
  },
  {
    id: 'library',
    name: `Library`,
    offset: 0x24d,
    mask: 0x02,
  },
  {
    id: 'mazeRace',
    name: `Maze Race`,
    offset: 0x2a8,
    mask: 0x40,
  },
  {
    id: 'desertLedge',
    name: `Desert Ledge`,
    offset: 0x2b0,
    mask: 0x40,
  },
  {
    id: 'lakeHyliaIsland',
    name: `Lake Hylia Island`,
    offset: 0x2b5,
    mask: 0x40,
  },
  {
    id: 'sunkenTreasure',
    name: `Sunken Treasure`,
    offset: 0x2bb,
    mask: 0x40,
  },
  {
    id: 'fluteSpot',
    name: `Flute Spot`,
    offset: 0x2aa,
    mask: 0x40,
  },
  // Dark World - Death Mountain - East
  {
    id: 'superbunnyCaveTop',
    name: `Superbunny Cave - Top`,
    offset: 0x1f0,
    mask: 0x10,
  },
  {
    id: 'superbunnyCaveBottom',
    name: `Superbunny Cave - Bottom`,
    offset: 0x1f0,
    mask: 0x20,
  },
  {
    id: 'hookshotCaveTopRight',
    name: `Hookshot Cave - Top Right`,
    offset: 0x078,
    mask: 0x10,
  },
  {
    id: 'hookshotCaveTopLeft',
    name: `Hookshot Cave - Top Left`,
    offset: 0x078,
    mask: 0x20,
  },
  {
    id: 'hookshotCaveBottomLeft',
    name: `Hookshot Cave - Bottom Left`,
    offset: 0x078,
    mask: 0x40,
  },
  {
    id: 'hookshotCaveBottomRight',
    name: `Hookshot Cave - Bottom Right`,
    offset: 0x078,
    mask: 0x80,
  },
  // Dark World - Death Mountain - West
  {
    id: 'spikeCave',
    name: `Spike Cave`,
    offset: 0x22e,
    mask: 0x10,
  },
  // Dark World - Mire
  {
    id: 'mireShedLeft',
    name: `Mire Shed - Left`,
    offset: 0x21a,
    mask: 0x10,
  },
  {
    id: 'mireShedRight',
    name: `Mire Shed - Right`,
    offset: 0x21a,
    mask: 0x20,
  },
  // Dark World - North East
  {
    id: 'catfish',
    name: `Catfish`,
    offset: 0x21a,
    mask: 0x20,
  },
  {
    id: 'pyramid',
    name: `Pyramid`,
    offset: 0x2db,
    mask: 0x40,
  },
  {
    id: 'pyramidFairySword',
    name: `Pyramid Fairy - Sword`,
    offset: 0x22c,
    mask: 0x10,
  },
  {
    id: 'pyramidFairyBow',
    name: `Pyramid Fairy - Bow`,
    offset: 0x22c,
    mask: 0x20,
  },
  // Dark World - North West
  {
    id: 'brewery',
    name: `Brewery`,
    offset: 0x20c,
    mask: 0x10,
  },
  {
    id: 'cShapedHouse',
    name: `C-Shaped House`,
    offset: 0x238,
    mask: 0x10,
  },
  {
    id: 'chestGame',
    name: `Chest Game`,
    offset: 0x20d,
    mask: 0x04,
  },
  {
    id: 'hammerPegs',
    name: `Hammer Pegs`,
    offset: 0x24f,
    mask: 0x04,
  },
  {
    id: 'bumperCave',
    name: `Bumper Cave`,
    offset: 0x2ca,
    mask: 0x40,
  },
  {
    id: 'blacksmith',
    name: `Blacksmith`,
    offset: 0x411,
    mask: 0x04,
  },
  {
    id: 'purpleChest',
    name: `Purple Chest`,
    offset: 0x3c9,
    mask: 0x10,
  },
  // Dark World - North West
  {
    id: 'hypeCaveTop',
    name: `Hype Cave - Top`,
    offset: 0x23c,
    mask: 0x10,
  },
  {
    id: 'hypeCaveMiddleRight',
    name: `Hype Cave - Middle Right`,
    offset: 0x23c,
    mask: 0x40,
  },
  {
    id: 'hypeCaveMiddleLeft',
    name: `Hype Cave - Middle Left`,
    offset: 0x23c,
    mask: 0x20,
  },
  {
    id: 'hypeCaveBottom',
    name: `Hype Cave - Bottom`,
    offset: 0x23c,
    mask: 0x80,
  },
  {
    id: 'stumpy',
    name: `Stumpy`,
    offset: 0x410,
    mask: 0x08,
  },
  {
    id: 'hypeCaveNPC',
    name: `Hype Cave - NPC`,
    offset: 0x23d,
    mask: 0x04,
  },
  {
    id: 'diggingGame',
    name: `Digging Game`,
    offset: 0x2e8,
    mask: 0x40,
  },
];

export default locations;
